// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBudzDiSPXFIEm4dUCW7gxovpKZX00bnMU',
    appId: '1:803401508957:android:b932631b4900d693da45b4',
    messagingSenderId: '803401508957',
    projectId: 'oia-smartwork',
    storageBucket: 'oia-smartwork.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwhs3FlYVihfBe7AusEjIYzrICsEkhZEA',
    appId: '1:803401508957:ios:209b37776d5762d8da45b4',
    messagingSenderId: '803401508957',
    projectId: 'oia-smartwork',
    storageBucket: 'oia-smartwork.appspot.com',
    androidClientId: '803401508957-e4rd95vns2r2mfmlf1mpmfvh4a2mis82.apps.googleusercontent.com',
    iosClientId: '803401508957-jaqh32pkdm8er5epc5vkaqptk6h7k1bh.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetao3',
  );
}
